# Generated by Django 5.2.1 on 2025-05-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='shift_type',
        ),
        migrations.DeleteModel(
            name='StaffAvailability',
        ),
    ]
