# Generated by Django 5.2.1 on 2025-05-30 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentassignment',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='staff.staffmember'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentassignment',
            unique_together={('staff_member', 'department')},
        ),
    ]
